const express=require('express');
const {verifyUser}=require('../middleware/auth');
const {login,signup,getUser, authUser,deleteuser,updateuser}=require('../controller/usercontroller');
const router=express.Router();
router.post('/usersignup',signup);
router.post('/userlogin',login);
router.get('/userget',verifyUser,getUser);
router.get('/check',verifyUser,authUser);
router.put('/updateuser/:id',updateuser);
router.delete('/deleteuser/:id',deleteuser);
module.exports=router;